// JSON & API Intro
// {
//  "id":"1",
//  "name": "Suhail"
// }

// [
//   {},
//   {},
//   {},
//   {},
//   {},
// ]

// Storing JSON data(from an API) in a variable for demonstration purposes
const jsonData = {
  status: 'OK',
  code: 200,
  locale: 'en_US',
  seed: null,
  total: 20,
  data: [
    {
      id: 1,
      firstname: 'Juanita',
      lastname: 'Kassulke',
      email: 'erling.kub@hotmail.com',
      phone: '+17545461714',
      birthday: '1962-11-25',
      gender: 'other',
      address: {
        id: 1,
        street: '6893 Donnelly Shore Suite 125',
        streetName: 'Ralph Estates',
        buildingNumber: '94278',
        city: 'Lake Maryam',
        zipcode: '48428-8290',
        country: 'French Polynesia',
        country_code: 'PF',
        latitude: -32.250651,
        longitude: 161.113533,
      },
      website: 'http://bailey.com',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 2,
      firstname: 'Amina',
      lastname: 'Macejkovic',
      email: 'kozey.gaston@morissette.com',
      phone: '+17574126289',
      birthday: '1998-03-06',
      gender: 'female',
      address: {
        id: 1,
        street: '427 Kilback Mills Suite 734',
        streetName: 'Leffler Spurs',
        buildingNumber: '44102',
        city: 'Hazleside',
        zipcode: '74077-7935',
        country: 'Tokelau',
        country_code: 'TK',
        latitude: -23.912477,
        longitude: 163.252902,
      },
      website: 'http://stark.com',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 3,
      firstname: 'Rudy',
      lastname: 'Medhurst',
      email: 'mclaughlin.meda@hotmail.com',
      phone: '+12176611247',
      birthday: '1999-12-18',
      gender: 'male',
      address: {
        id: 1,
        street: '6486 Stehr Mall Suite 477',
        streetName: 'Hickle Flats',
        buildingNumber: '745',
        city: 'Port Jayceburgh',
        zipcode: '19950',
        country: 'Mauritania',
        country_code: 'MR',
        latitude: 8.944039,
        longitude: -37.733827,
      },
      website: 'http://hegmann.com',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 4,
      firstname: 'Melyssa',
      lastname: 'Champlin',
      email: 'patsy41@hotmail.com',
      phone: '+17658830373',
      birthday: '1984-10-07',
      gender: 'female',
      address: {
        id: 1,
        street: '4532 Michael Lake',
        streetName: 'Deckow Mills',
        buildingNumber: '7023',
        city: 'Cruickshankchester',
        zipcode: '78849',
        country: 'Belgium',
        country_code: 'BE',
        latitude: -55.440769,
        longitude: -40.888314,
      },
      website: 'http://bernier.info',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 5,
      firstname: 'Kristina',
      lastname: 'Denesik',
      email: 'tillman.tristin@yahoo.com',
      phone: '+12238675771',
      birthday: '1961-03-23',
      gender: 'female',
      address: {
        id: 1,
        street: '812 Cole Ridges',
        streetName: 'Loren Trafficway',
        buildingNumber: '68011',
        city: "D'Amoreland",
        zipcode: '25835-2316',
        country: 'Martinique',
        country_code: 'MQ',
        latitude: 57.329396,
        longitude: -16.621448,
      },
      website: 'http://jenkins.com',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 6,
      firstname: 'Betty',
      lastname: 'Nolan',
      email: 'vance97@yahoo.com',
      phone: '+12708424120',
      birthday: '1958-05-15',
      gender: 'female',
      address: {
        id: 1,
        street: '73638 Mario Corner Suite 255',
        streetName: 'Friesen Lodge',
        buildingNumber: '61458',
        city: 'Fadelton',
        zipcode: '40045-0283',
        country: 'Syria',
        country_code: 'SY',
        latitude: -87.242861,
        longitude: -137.0144,
      },
      website: 'http://flatley.info',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 7,
      firstname: 'Rod',
      lastname: 'Runte',
      email: 'awilderman@luettgen.biz',
      phone: '+12405744472',
      birthday: '1976-09-09',
      gender: 'other',
      address: {
        id: 1,
        street: '668 Alexie River Suite 389',
        streetName: 'Krajcik Creek',
        buildingNumber: '76246',
        city: 'North Jackieside',
        zipcode: '64982',
        country: 'Malta',
        country_code: 'MT',
        latitude: -70.743796,
        longitude: 100.152134,
      },
      website: 'http://powlowski.biz',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 8,
      firstname: 'Odessa',
      lastname: 'Kuhn',
      email: 'effie56@gmail.com',
      phone: '+13416315520',
      birthday: '1973-08-08',
      gender: 'other',
      address: {
        id: 1,
        street: '9929 Walker Estate',
        streetName: 'Kling Flats',
        buildingNumber: '5195',
        city: 'Olsonstad',
        zipcode: '66654',
        country: 'Guadeloupe',
        country_code: 'GP',
        latitude: -7.066337,
        longitude: 54.323746,
      },
      website: 'http://gottlieb.info',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 9,
      firstname: 'Tito',
      lastname: 'Bogisich',
      email: 'dedric.rolfson@watsica.com',
      phone: '+18178510935',
      birthday: '1962-10-28',
      gender: 'male',
      address: {
        id: 1,
        street: '162 Jodie Keys Suite 630',
        streetName: 'Emery Terrace',
        buildingNumber: '913',
        city: 'Cristobalmouth',
        zipcode: '32274-5121',
        country: 'Thailand',
        country_code: 'TH',
        latitude: 48.453475,
        longitude: -59.589794,
      },
      website: 'http://turner.com',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 10,
      firstname: 'Johanna',
      lastname: 'Prosacco',
      email: 'batz.preston@hansen.com',
      phone: '+14403891165',
      birthday: '1944-03-27',
      gender: 'female',
      address: {
        id: 1,
        street: '1241 Nikolaus Circle Apt. 008',
        streetName: 'Prosacco Plaza',
        buildingNumber: '7429',
        city: 'Port Chaunceymouth',
        zipcode: '64355-5799',
        country: 'Bulgaria',
        country_code: 'BG',
        latitude: 82.935014,
        longitude: 14.40714,
      },
      website: 'http://schiller.biz',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 11,
      firstname: 'Bret',
      lastname: 'Leannon',
      email: 'elinor59@hotmail.com',
      phone: '+19716052629',
      birthday: '2005-08-20',
      gender: 'male',
      address: {
        id: 1,
        street: '7003 Adan Plaza',
        streetName: 'Rippin Throughway',
        buildingNumber: '1508',
        city: 'Lukasbury',
        zipcode: '18925',
        country: 'Estonia',
        country_code: 'EE',
        latitude: -51.690806,
        longitude: 116.593397,
      },
      website: 'http://ullrich.com',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 12,
      firstname: 'Joan',
      lastname: 'Kris',
      email: 'geovanny85@kiehn.com',
      phone: '+18054138264',
      birthday: '1969-12-01',
      gender: 'male',
      address: {
        id: 1,
        street: '425 Josefa Extensions',
        streetName: 'Madie Mission',
        buildingNumber: '26403',
        city: 'VonRuedenburgh',
        zipcode: '92332',
        country: 'Mexico',
        country_code: 'MX',
        latitude: -61.171064,
        longitude: -96.010261,
      },
      website: 'http://hand.info',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 13,
      firstname: 'Buddy',
      lastname: 'Johnston',
      email: 'gretchen55@gmail.com',
      phone: '+18786087219',
      birthday: '1945-03-18',
      gender: 'other',
      address: {
        id: 1,
        street: '589 Serenity Glen Apt. 281',
        streetName: 'Brady Squares',
        buildingNumber: '323',
        city: 'East Cadeville',
        zipcode: '98074',
        country: 'Bangladesh',
        country_code: 'BD',
        latitude: 76.527849,
        longitude: -155.650076,
      },
      website: 'http://krajcik.org',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 14,
      firstname: 'Flavie',
      lastname: 'Brekke',
      email: 'bwilderman@cronin.biz',
      phone: '+16109100862',
      birthday: '1974-05-25',
      gender: 'female',
      address: {
        id: 1,
        street: '72010 Joesph Forge',
        streetName: 'Wunsch Oval',
        buildingNumber: '77241',
        city: 'North Douglasbury',
        zipcode: '70936',
        country: 'Antarctica',
        country_code: 'AQ',
        latitude: 32.234069,
        longitude: -88.783152,
      },
      website: 'http://stark.biz',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 15,
      firstname: 'Watson',
      lastname: 'Hermann',
      email: 'lrunolfsson@crona.com',
      phone: '+17606774369',
      birthday: '1978-01-12',
      gender: 'male',
      address: {
        id: 1,
        street: '9489 Addison Tunnel Suite 535',
        streetName: 'Schulist Run',
        buildingNumber: '455',
        city: 'Ebertfurt',
        zipcode: '32155',
        country: 'Maldives',
        country_code: 'MV',
        latitude: -28.155025,
        longitude: -132.679781,
      },
      website: 'http://mcdermott.biz',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 16,
      firstname: 'Omer',
      lastname: 'Hettinger',
      email: 'goldner.justina@hermann.org',
      phone: '+19479048331',
      birthday: '1994-01-31',
      gender: 'male',
      address: {
        id: 1,
        street: '2227 Veum Lodge',
        streetName: 'Green Coves',
        buildingNumber: '81552',
        city: 'Norenetown',
        zipcode: '23816-5977',
        country: 'Fiji',
        country_code: 'FJ',
        latitude: 20.997705,
        longitude: -179.210655,
      },
      website: 'http://sipes.com',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 17,
      firstname: 'Kimberly',
      lastname: 'Hermiston',
      email: 'stoltenberg.dedric@yahoo.com',
      phone: '+18085943918',
      birthday: '1960-02-03',
      gender: 'female',
      address: {
        id: 1,
        street: '71474 Krystal Rest',
        streetName: 'Kaelyn Cape',
        buildingNumber: '53367',
        city: 'South Samarachester',
        zipcode: '96975',
        country: 'Kiribati',
        country_code: 'KI',
        latitude: -53.532608,
        longitude: 107.191627,
      },
      website: 'http://schumm.net',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 18,
      firstname: 'Adonis',
      lastname: 'Bartoletti',
      email: 'elliot.gaylord@hotmail.com',
      phone: '+13529363118',
      birthday: '2001-11-16',
      gender: 'other',
      address: {
        id: 1,
        street: '186 Jacobi Center',
        streetName: 'Keanu Circles',
        buildingNumber: '694',
        city: 'Jefferyfurt',
        zipcode: '78097-7397',
        country: 'Niue',
        country_code: 'NU',
        latitude: -65.299682,
        longitude: 93.03509,
      },
      website: 'http://schulist.com',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 19,
      firstname: 'Buster',
      lastname: 'Kertzmann',
      email: 'urban70@hayes.com',
      phone: '+19096086303',
      birthday: '2003-10-23',
      gender: 'male',
      address: {
        id: 1,
        street: '52079 Botsford Harbor Apt. 744',
        streetName: 'Brakus Freeway',
        buildingNumber: '980',
        city: 'Lake Savanna',
        zipcode: '36362',
        country: 'Paraguay',
        country_code: 'PY',
        latitude: 51.249898,
        longitude: 63.171605,
      },
      website: 'http://romaguera.com',
      image: 'http://placeimg.com/640/480/people',
    },
    {
      id: 20,
      firstname: 'Ines',
      lastname: 'Klocko',
      email: 'hayes.lilliana@gmail.com',
      phone: '+18284356340',
      birthday: '1951-06-09',
      gender: 'female',
      address: {
        id: 1,
        street: '92016 Runolfsson Summit',
        streetName: 'Brody Lake',
        buildingNumber: '659',
        city: 'South Wilton',
        zipcode: '31329-6363',
        country: 'Cambodia',
        country_code: 'KH',
        latitude: 11.737477,
        longitude: -111.679023,
      },
      website: 'http://gerlach.net',
      image: 'http://placeimg.com/640/480/people',
    },
  ],
};
